### ISSUE TITLE
URL in lowercase ...

### ISSUE THREAD

**Issue by edyan** [sugarcrm/rest-php-client#12]
Hi,

I want to use your tool but I see there : https://github.com/sugarcrm/rest-php-client/blob/master/src/Helpers/Helpers.php#L22 that you force the url to be in lowercase ... how to manage when we have Sugar in a subfolder (_http://localhost/SugarTest_) ? 

In that case, I get a 404

Thanks

**Comment by MichaelJ2324** [comment]
Thank you for pointing this out. I created a PR to resolve this issue. I am not sure what my initial intention was with the force to lower case (I'm thinking initially had something to do with ease of replacing the proper elements), but it is not necessary.
