### ISSUE TITLE
Compability with version 6.5

### ISSUE THREAD

**Issue by klapifoch** [sugarcrm/rest-php-client#25]
I tried to use it with sugar crm 6.5 with any luck, is there a fork for this purpose?

**Comment by MichaelJ2324** [comment]
The architecture setup in v1.x of the Rest Client could work for a Sugar 6.5 Rest Client, however it was never something that was going to be built within this repository, as this was strictly meant for Sugar 7 REST v10 API. Version 2 (in beta currently) of the Client would only work for a true REST API, which Sugar Sugar 6.5 did not have.

You are more than welcome to Fork it and build out the Endpoints for Sugar 6.5.x.
