### ISSUE TITLE
SugarCRM 8 and API v_11

### ISSUE THREAD

**Issue by nissyre** [sugarcrm/rest-php-client#37]
Hi,
  are you going to upgrade this rest client to work with SugarCRM 8 and API v_11??

**Comment by abhiyanp** [comment]
I was able to get it working by setting the version parameter as follows.

**Comment by parithibang** [comment]
@abhiyanp 
I have tried this is not been working for me. The code flow is from 
`setVersion()->setAPIUrl()->configureAPIURL()`. 
Where they are using `intval()` method which converts `11_1` to `11`. The resulting output would be `http://192.168.199.48/rest/v11/` for the above case and not `http://192.168.199.48/rest/v11_1/`

**Comment by MichaelJ2324** [comment]
I submitted an update for this issue. Will cut a release as soon as it is merged. Please know, you can always submit a PR to the repo yourself if you come across and issue and we will review and merge in updates as well.

**Comment by MichaelJ2324** [comment]
Release 1.4.5 resolves this issue.
