### ISSUE TITLE
Implementation of new endpoints: count & duplicateCheck

### ISSUE THREAD

**Issue by dnlk17** [sugarcrm/rest-php-client#39]
Hi,
thank you for providing the rest-php-client. 💙

I needed a new endpoint (`/<Module>/duplicateCheck`) that was not yet included in the client, so I implemented it and created a [pull request](https://github.com/sugarcrm/rest-php-client/pull/38).
In addition to that I saw the request for having the `/<Module>/count` endpoint available (issue #36), therefore I also added it in my changes.

Please give me feedback if my PR fulfills your expectations and requirements.

Best regards,
Daniel

**Comment by dnlk17** [comment]
Thank you for merging my changes into master. ❤️ 
Is there a new release planned in the near future?

@geraldclark / @MichaelJ2324

**Comment by geraldclark** [comment]
Hi @dnlk17, Sorry for the delay in response. There is a v2 planned for release in the future:
https://github.com/sugarcrm/rest-php-client/tree/2.0 . You are more than welcome to check it :)

**Comment by MichaelJ2324** [comment]
Hi @dnlk17 ,

We did cut a new v1.x release today, which now has your DuplicateCheck and Count endpoints included. v2.0 has beta releases and a completely new structure, and that is our primary focus, so we apologize for taking so long to cut a new v1 release.
