### ISSUE TITLE
Compatiblity with SugarCRM 7.10

### ISSUE THREAD

**Issue by Putr** [sugarcrm/rest-php-client#40]
This project does not seem to be compatible with SugarCRM API.

API of SugarCRM 7.10 requires a path like this:
 `/api/oauth/access_token`
while this client is looking for
`/rest/v10/oauth/access_token`

**Comment by geraldclark** [comment]
Hi @Putr,

The Sugar REST URLs are in the format of `/rest/<version>/oauth/access_token` as documented here: 
https://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_8.3/Integration/Web_Services/

Can you let me know where you're seeing `/api/oauth/access_token`?

**Comment by Putr** [comment]
https://docs.suitecrm.com/developer/api/version-8/configure-authentication/

Also, my install returns an error when requesting /api/oauth/access_token and a 404 when accesing the /rest/ version.

**Comment by Putr** [comment]
Damn. Sugar vs. Suite. Damn.
